### ISSUE TITLE
Way to change the port of the clone url

### ISSUE THREAD

**Issue by Hertex** [dockhippie/gitea#5]
I am currently trying to change the URL that is displayed to clone a repository over Http. I managed to change the domain but I can't figure out how to change the port. By using the install page you can change it by editing the "application URL". (see screenshot)

The default URL is "http://gitea:3000".

I need to change it because I don't want to expose a different port than the one that Gitea is using (e.g. Gitea uses 3000 and I want to expose 33333). The goal is that the URL to clone a repo should show something like "http://example.com:33333/User/repo.git".

I already tried to change various variables like `GITEA_SERVER_ROOT_URL` but it either doesn't work or I can't access Gitea anymore.

![gitea_application_url](https://user-images.githubusercontent.com/47070289/62813342-8790ed80-bb0a-11e9-98e8-6f49243aa63c.PNG)

**Comment by tboerger** [comment]
You can configure everything by env variables, a reference of the available env variables you can see at https://github.com/dockhippie/gitea#available-environment-variables. To change the displayed public URL you can set `GITEA_SERVER_ROOT_URL = ${GITEA_SERVER_PROTOCOL}://${GITEA_SERVER_DOMAIN}:${GITEA_SERVER_HTTP_PORT}/` to a different value, like `GITEA_SERVER_ROOT_URL = http://gitea:3000`.
